/*
 * Copyright (c) 2007 Thomas Weise for sigoa
 * Simple Interface for Global Optimization Algorithms
 * http://www.sigoa.org/
 * 
 * E-Mail           : info@sigoa.org
 * Creation Date    : 2007-12-30
 * Creator          : Thomas Weise
 * Original Filename: org.sfc.math.matrix.Determinante.java
 * Last modification: 2007-12-30
 *                by: Thomas Weise
 * 
 * License          : GNU LESSER GENERAL PUBLIC LICENSE
 *                    Version 2.1, February 1999
 *                    You should have received a copy of this license along
 *                    with this library; if not, write to theFree Software
 *                    Foundation, Inc. 51 Franklin Street, Fifth Floor,
 *                    Boston, MA 02110-1301, USA or download the license
 *                    under http://www.gnu.org/licenses/lgpl.html or
 *                    http://www.gnu.org/copyleft/lesser.html.
 *                    
 * Warranty         : This software is provided "as is" without any
 *                    warranty; without even the implied warranty of
 *                    merchantability or fitness for a particular purpose.
 *                    See the Gnu Lesser General Public License for more
 *                    details.
 */

package org.sfc.math.matrix;

/**
 * To calculate determinants, we use again three different approaches: 1.
 * For small matrices, hard coded Laplace-Development. It's code was
 * auto-generated by the code generator that can be found in the archive
 * /doc/matrix/code_generators.zip. It is not guaranteed that the generated
 * code will be the global optimum, however, it is a local optimum. 2. For
 * matrices bigger up to a special size, the Gaussian elimination is used
 * to reach triangular form. 3. On bigger matrices, it seems to be fastest
 * to use the L-U decomposition.
 */
public final class Determinante {
  /** The iteration threshold */
  public static final int LU_THRESHOLD = 1420;

  /** a private interface for fast matrix determinant calculation */
  private static interface IDirectDet {
    /**
     * calculate the determinant
     * 
     * @param mat
     *          The matrix data.
     * @return the determinant
     */
    public double det(double mat[]);
  }

  /** list for fast matrix calculation */
  private final static IDirectDet[] FAST_DET = {
  // l = 1, that means we handle all 1x1 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          return mat[0];
        }
      },
      // l = 2, that means we handle all 2x2 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          return ((mat[0] * mat[3]) - (mat[1] * mat[2]));
        }
      },
      // l = 3, that means we handle all 3x3 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          double d3 = mat[3];
          double d4 = mat[4];
          double d5 = mat[5];
          double d6 = mat[6];
          double d7 = mat[7];
          double d8 = mat[8];
          return ((mat[0] * ((d4 * d8) - (d5 * d7)))
              - (mat[1] * ((d3 * d8) - (d5 * d6))) + (mat[2] * ((d3 * d7) - (d4 * d6))));
        }
      },
      // l = 4, that means we handle all 4x4 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          /* 16 array hits, 5 +, 18 -, 28 *, 18 variables */

          double d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18;

          d1 = mat[15];
          d2 = mat[11];
          d3 = mat[7];
          d4 = mat[4];
          d5 = mat[5];
          d6 = mat[14];
          d7 = mat[10];
          d8 = mat[6];
          d9 = mat[8];
          d10 = mat[13];
          d11 = mat[9];
          d12 = mat[12];
          d13 = (d7 * d1);
          d14 = (d2 * d6);
          d15 = (d11 * d1);
          d16 = (d2 * d10);
          d1 = (d9 * d1);
          d2 = (d2 * d12);
          d17 = (d11 * d6);
          d18 = (d7 * d10);
          d6 = (d9 * d6);
          d7 = (d7 * d12);
          d9 = (d9 * d10);
          d10 = (d11 * d12);

          return ((mat[0] * ((d5 * (d13 - d14)) - (d8 * (d15 - d16)) + (d3 * (d17 - d18))))
              - (mat[1] * ((d4 * (d13 - d14)) - (d8 * (d1 - d2)) + (d3 * (d6 - d7))))
              + (mat[2] * ((d4 * (d15 - d16)) - (d5 * (d1 - d2)) + (d3 * (d9 - d10)))) - (mat[3] * ((d4 * (d17 - d18))
              - (d5 * (d6 - d7)) + (d8 * (d9 - d10)))));

        }
      },
      // l = 5, that means we handle all 5x5 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          /* 25 array hits, 17 +, 32 -, 75 *, 38 variables */

          double d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38;

          d1 = mat[24];
          d2 = mat[19];
          d3 = mat[14];
          d4 = mat[9];
          d5 = mat[5];
          d6 = mat[6];
          d7 = mat[7];
          d8 = mat[23];
          d9 = mat[18];
          d10 = mat[13];
          d11 = mat[8];
          d12 = mat[10];
          d13 = mat[11];
          d14 = mat[22];
          d15 = mat[17];
          d16 = mat[12];
          d17 = mat[15];
          d18 = mat[21];
          d19 = mat[16];
          d20 = mat[20];
          d21 = (d9 * d1);
          d22 = (d2 * d8);
          d23 = (d15 * d1);
          d24 = (d2 * d14);
          d25 = (d19 * d1);
          d26 = (d2 * d18);
          d1 = (d17 * d1);
          d2 = (d2 * d20);
          d27 = (d15 * d8);
          d28 = (d9 * d14);
          d29 = (d19 * d8);
          d30 = (d9 * d18);
          d8 = (d17 * d8);
          d9 = (d9 * d20);
          d31 = (d19 * d14);
          d32 = (d15 * d18);
          d14 = (d17 * d14);
          d15 = (d15 * d20);
          d17 = (d17 * d18);
          d18 = (d19 * d20);
          d19 = (d21 - d22);
          d20 = (d23 - d24);
          d21 = (d25 - d26);
          d1 = (d1 - d2);
          d2 = (d27 - d28);
          d22 = (d29 - d30);
          d8 = (d8 - d9);
          d9 = (d31 - d32);
          d14 = (d14 - d15);
          d15 = (d17 - d18);
          d17 = (d16 * d19);
          d18 = (d10 * d20);
          d23 = (d3 * d2);
          d24 = (d13 * d19);
          d25 = (d10 * d21);
          d26 = (d3 * d22);
          d19 = (d12 * d19);
          d27 = (d10 * d1);
          d28 = (d3 * d8);
          d29 = (d13 * d20);
          d30 = (d16 * d21);
          d31 = (d3 * d9);
          d20 = (d12 * d20);
          d32 = (d16 * d1);
          d33 = (d3 * d14);
          d21 = (d12 * d21);
          d1 = (d13 * d1);
          d3 = (d3 * d15);
          d34 = (d13 * d2);
          d35 = (d16 * d22);
          d36 = (d10 * d9);
          d2 = (d12 * d2);
          d37 = (d16 * d8);
          d38 = (d10 * d14);
          d22 = (d12 * d22);
          d8 = (d13 * d8);
          d10 = (d10 * d15);
          d9 = (d12 * d9);
          d12 = (d13 * d14);
          d13 = (d16 * d15);
          d14 = (d17 - d18 + d23);
          d15 = (d24 - d25 + d26);
          d16 = (d19 - d27 + d28);
          d17 = (d29 - d30 + d31);
          d18 = (d20 - d32 + d33);
          d1 = (d21 - d1 + d3);
          d3 = (d34 - d35 + d36);
          d2 = (d2 - d37 + d38);
          d8 = (d22 - d8 + d10);
          d9 = (d9 - d12 + d13);

          return ((mat[0] * ((d6 * d14) - (d7 * d15) + (d11 * d17) - (d4 * d3)))
              - (mat[1] * ((d5 * d14) - (d7 * d16) + (d11 * d18) - (d4 * d2)))
              + (mat[2] * ((d5 * d15) - (d6 * d16) + (d11 * d1) - (d4 * d8)))
              - (mat[3] * ((d5 * d17) - (d6 * d18) + (d7 * d1) - (d4 * d9))) + (mat[4] * ((d5 * d3)
              - (d6 * d2) + (d7 * d8) - (d11 * d9))));

        }
      },
      // l = 6, that means we handle all 6x6 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          /* 36 array hits, 49 +, 80 -, 186 *, 75 variables */

          double d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38, d39, d40, d41, d42, d43, d44, d45, d46, d47, d48, d49, d50, d51, d52, d53, d54, d55, d56, d57, d58, d59, d60, d61, d62, d63, d64, d65, d66, d67, d68, d69, d70, d71, d72, d73, d74, d75;

          d1 = mat[35];
          d2 = mat[29];
          d3 = mat[23];
          d4 = mat[17];
          d5 = mat[11];
          d6 = mat[6];
          d7 = mat[7];
          d8 = mat[8];
          d9 = mat[9];
          d10 = mat[34];
          d11 = mat[28];
          d12 = mat[22];
          d13 = mat[16];
          d14 = mat[10];
          d15 = mat[12];
          d16 = mat[13];
          d17 = mat[14];
          d18 = mat[33];
          d19 = mat[27];
          d20 = mat[21];
          d21 = mat[15];
          d22 = mat[18];
          d23 = mat[19];
          d24 = mat[32];
          d25 = mat[26];
          d26 = mat[20];
          d27 = mat[24];
          d28 = mat[31];
          d29 = mat[25];
          d30 = mat[30];
          d31 = (d11 * d1);
          d32 = (d2 * d10);
          d33 = (d19 * d1);
          d34 = (d2 * d18);
          d35 = (d25 * d1);
          d36 = (d2 * d24);
          d37 = (d29 * d1);
          d38 = (d2 * d28);
          d1 = (d27 * d1);
          d2 = (d2 * d30);
          d39 = (d19 * d10);
          d40 = (d11 * d18);
          d41 = (d25 * d10);
          d42 = (d11 * d24);
          d43 = (d29 * d10);
          d44 = (d11 * d28);
          d10 = (d27 * d10);
          d11 = (d11 * d30);
          d45 = (d25 * d18);
          d46 = (d19 * d24);
          d47 = (d29 * d18);
          d48 = (d19 * d28);
          d18 = (d27 * d18);
          d19 = (d19 * d30);
          d49 = (d29 * d24);
          d50 = (d25 * d28);
          d24 = (d27 * d24);
          d25 = (d25 * d30);
          d27 = (d27 * d28);
          d28 = (d29 * d30);
          d29 = (d31 - d32);
          d30 = (d33 - d34);
          d31 = (d35 - d36);
          d32 = (d37 - d38);
          d1 = (d1 - d2);
          d2 = (d39 - d40);
          d33 = (d41 - d42);
          d34 = (d43 - d44);
          d10 = (d10 - d11);
          d11 = (d45 - d46);
          d35 = (d47 - d48);
          d18 = (d18 - d19);
          d19 = (d49 - d50);
          d24 = (d24 - d25);
          d25 = (d27 - d28);
          d27 = (d20 * d29);
          d28 = (d12 * d30);
          d36 = (d3 * d2);
          d37 = (d26 * d29);
          d38 = (d12 * d31);
          d39 = (d3 * d33);
          d40 = (d23 * d29);
          d41 = (d12 * d32);
          d42 = (d3 * d34);
          d29 = (d22 * d29);
          d43 = (d12 * d1);
          d44 = (d3 * d10);
          d45 = (d26 * d30);
          d46 = (d20 * d31);
          d47 = (d3 * d11);
          d48 = (d23 * d30);
          d49 = (d20 * d32);
          d50 = (d3 * d35);
          d30 = (d22 * d30);
          d51 = (d20 * d1);
          d52 = (d3 * d18);
          d53 = (d23 * d31);
          d54 = (d26 * d32);
          d55 = (d3 * d19);
          d31 = (d22 * d31);
          d56 = (d26 * d1);
          d57 = (d3 * d24);
          d32 = (d22 * d32);
          d1 = (d23 * d1);
          d3 = (d3 * d25);
          d58 = (d26 * d2);
          d59 = (d20 * d33);
          d60 = (d12 * d11);
          d61 = (d23 * d2);
          d62 = (d20 * d34);
          d63 = (d12 * d35);
          d2 = (d22 * d2);
          d64 = (d20 * d10);
          d65 = (d12 * d18);
          d66 = (d23 * d33);
          d67 = (d26 * d34);
          d68 = (d12 * d19);
          d33 = (d22 * d33);
          d69 = (d26 * d10);
          d70 = (d12 * d24);
          d34 = (d22 * d34);
          d10 = (d23 * d10);
          d12 = (d12 * d25);
          d71 = (d23 * d11);
          d72 = (d26 * d35);
          d73 = (d20 * d19);
          d11 = (d22 * d11);
          d74 = (d26 * d18);
          d75 = (d20 * d24);
          d35 = (d22 * d35);
          d18 = (d23 * d18);
          d20 = (d20 * d25);
          d19 = (d22 * d19);
          d22 = (d23 * d24);
          d23 = (d26 * d25);
          d24 = (d27 - d28 + d36);
          d25 = (d37 - d38 + d39);
          d26 = (d40 - d41 + d42);
          d27 = (d29 - d43 + d44);
          d28 = (d45 - d46 + d47);
          d29 = (d48 - d49 + d50);
          d30 = (d30 - d51 + d52);
          d36 = (d53 - d54 + d55);
          d31 = (d31 - d56 + d57);
          d1 = (d32 - d1 + d3);
          d3 = (d58 - d59 + d60);
          d32 = (d61 - d62 + d63);
          d2 = (d2 - d64 + d65);
          d37 = (d66 - d67 + d68);
          d33 = (d33 - d69 + d70);
          d10 = (d34 - d10 + d12);
          d12 = (d71 - d72 + d73);
          d11 = (d11 - d74 + d75);
          d18 = (d35 - d18 + d20);
          d19 = (d19 - d22 + d23);
          d20 = (d17 * d24);
          d22 = (d21 * d25);
          d23 = (d13 * d28);
          d34 = (d4 * d3);
          d35 = (d16 * d24);
          d38 = (d21 * d26);
          d39 = (d13 * d29);
          d40 = (d4 * d32);
          d24 = (d15 * d24);
          d41 = (d21 * d27);
          d42 = (d13 * d30);
          d43 = (d4 * d2);
          d44 = (d16 * d25);
          d45 = (d17 * d26);
          d46 = (d13 * d36);
          d47 = (d4 * d37);
          d25 = (d15 * d25);
          d48 = (d17 * d27);
          d49 = (d13 * d31);
          d50 = (d4 * d33);
          d26 = (d15 * d26);
          d27 = (d16 * d27);
          d51 = (d13 * d1);
          d52 = (d4 * d10);
          d53 = (d16 * d28);
          d54 = (d17 * d29);
          d55 = (d21 * d36);
          d56 = (d4 * d12);
          d28 = (d15 * d28);
          d57 = (d17 * d30);
          d58 = (d21 * d31);
          d59 = (d4 * d11);
          d29 = (d15 * d29);
          d30 = (d16 * d30);
          d60 = (d21 * d1);
          d61 = (d4 * d18);
          d36 = (d15 * d36);
          d31 = (d16 * d31);
          d1 = (d17 * d1);
          d4 = (d4 * d19);
          d62 = (d16 * d3);
          d63 = (d17 * d32);
          d64 = (d21 * d37);
          d65 = (d13 * d12);
          d3 = (d15 * d3);
          d66 = (d17 * d2);
          d67 = (d21 * d33);
          d68 = (d13 * d11);
          d32 = (d15 * d32);
          d2 = (d16 * d2);
          d69 = (d21 * d10);
          d70 = (d13 * d18);
          d37 = (d15 * d37);
          d33 = (d16 * d33);
          d10 = (d17 * d10);
          d13 = (d13 * d19);
          d12 = (d15 * d12);
          d11 = (d16 * d11);
          d15 = (d17 * d18);
          d16 = (d21 * d19);
          d17 = (d20 - d22 + d23 - d34);
          d18 = (d35 - d38 + d39 - d40);
          d19 = (d24 - d41 + d42 - d43);
          d20 = (d44 - d45 + d46 - d47);
          d21 = (d25 - d48 + d49 - d50);
          d22 = (d26 - d27 + d51 - d52);
          d23 = (d53 - d54 + d55 - d56);
          d24 = (d28 - d57 + d58 - d59);
          d25 = (d29 - d30 + d60 - d61);
          d1 = (d36 - d31 + d1 - d4);
          d4 = (d62 - d63 + d64 - d65);
          d3 = (d3 - d66 + d67 - d68);
          d2 = (d32 - d2 + d69 - d70);
          d10 = (d37 - d33 + d10 - d13);
          d11 = (d12 - d11 + d15 - d16);

          return ((mat[0] * ((d7 * d17) - (d8 * d18) + (d9 * d20)
              - (d14 * d23) + (d5 * d4)))
              - (mat[1] * ((d6 * d17) - (d8 * d19) + (d9 * d21)
                  - (d14 * d24) + (d5 * d3)))
              + (mat[2] * ((d6 * d18) - (d7 * d19) + (d9 * d22)
                  - (d14 * d25) + (d5 * d2)))
              - (mat[3] * ((d6 * d20) - (d7 * d21) + (d8 * d22)
                  - (d14 * d1) + (d5 * d10)))
              + (mat[4] * ((d6 * d23) - (d7 * d24) + (d8 * d25)
                  - (d9 * d1) + (d5 * d11))) - (mat[5] * ((d6 * d4)
              - (d7 * d3) + (d8 * d2) - (d9 * d10) + (d14 * d11))));

        }
      },
      // l = 7, that means we handle all 7x7 matrices here
      new IDirectDet() {
        public double det(double[] mat) {
          /* 49 array hits, 129 +, 192 -, 441 *, 158 variables */

          double d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38, d39, d40, d41, d42, d43, d44, d45, d46, d47, d48, d49, d50, d51, d52, d53, d54, d55, d56, d57, d58, d59, d60, d61, d62, d63, d64, d65, d66, d67, d68, d69, d70, d71, d72, d73, d74, d75, d76, d77, d78, d79, d80, d81, d82, d83, d84, d85, d86, d87, d88, d89, d90, d91, d92, d93, d94, d95, d96, d97, d98, d99, d100, d101, d102, d103, d104, d105, d106, d107, d108, d109, d110, d111, d112, d113, d114, d115, d116, d117, d118, d119, d120, d121, d122, d123, d124, d125, d126, d127, d128, d129, d130, d131, d132, d133, d134, d135, d136, d137, d138, d139, d140, d141, d142, d143, d144, d145, d146, d147, d148, d149, d150, d151, d152, d153, d154, d155, d156, d157, d158;

          d1 = mat[48];
          d2 = mat[41];
          d3 = mat[34];
          d4 = mat[27];
          d5 = mat[20];
          d6 = mat[13];
          d7 = mat[7];
          d8 = mat[8];
          d9 = mat[9];
          d10 = mat[10];
          d11 = mat[11];
          d12 = mat[47];
          d13 = mat[40];
          d14 = mat[33];
          d15 = mat[26];
          d16 = mat[19];
          d17 = mat[12];
          d18 = mat[14];
          d19 = mat[15];
          d20 = mat[16];
          d21 = mat[17];
          d22 = mat[46];
          d23 = mat[39];
          d24 = mat[32];
          d25 = mat[25];
          d26 = mat[18];
          d27 = mat[21];
          d28 = mat[22];
          d29 = mat[23];
          d30 = mat[45];
          d31 = mat[38];
          d32 = mat[31];
          d33 = mat[24];
          d34 = mat[28];
          d35 = mat[29];
          d36 = mat[44];
          d37 = mat[37];
          d38 = mat[30];
          d39 = mat[35];
          d40 = mat[43];
          d41 = mat[36];
          d42 = mat[42];
          d43 = (d13 * d1);
          d44 = (d2 * d12);
          d45 = (d23 * d1);
          d46 = (d2 * d22);
          d47 = (d31 * d1);
          d48 = (d2 * d30);
          d49 = (d37 * d1);
          d50 = (d2 * d36);
          d51 = (d41 * d1);
          d52 = (d2 * d40);
          d1 = (d39 * d1);
          d2 = (d2 * d42);
          d53 = (d23 * d12);
          d54 = (d13 * d22);
          d55 = (d31 * d12);
          d56 = (d13 * d30);
          d57 = (d37 * d12);
          d58 = (d13 * d36);
          d59 = (d41 * d12);
          d60 = (d13 * d40);
          d12 = (d39 * d12);
          d13 = (d13 * d42);
          d61 = (d31 * d22);
          d62 = (d23 * d30);
          d63 = (d37 * d22);
          d64 = (d23 * d36);
          d65 = (d41 * d22);
          d66 = (d23 * d40);
          d22 = (d39 * d22);
          d23 = (d23 * d42);
          d67 = (d37 * d30);
          d68 = (d31 * d36);
          d69 = (d41 * d30);
          d70 = (d31 * d40);
          d30 = (d39 * d30);
          d31 = (d31 * d42);
          d71 = (d41 * d36);
          d72 = (d37 * d40);
          d36 = (d39 * d36);
          d37 = (d37 * d42);
          d39 = (d39 * d40);
          d40 = (d41 * d42);
          d41 = (d43 - d44);
          d42 = (d45 - d46);
          d43 = (d47 - d48);
          d44 = (d49 - d50);
          d45 = (d51 - d52);
          d1 = (d1 - d2);
          d2 = (d53 - d54);
          d46 = (d55 - d56);
          d47 = (d57 - d58);
          d48 = (d59 - d60);
          d12 = (d12 - d13);
          d13 = (d61 - d62);
          d49 = (d63 - d64);
          d50 = (d65 - d66);
          d22 = (d22 - d23);
          d23 = (d67 - d68);
          d51 = (d69 - d70);
          d30 = (d30 - d31);
          d31 = (d71 - d72);
          d36 = (d36 - d37);
          d37 = (d39 - d40);
          d39 = (d24 * d41);
          d40 = (d14 * d42);
          d52 = (d3 * d2);
          d53 = (d32 * d41);
          d54 = (d14 * d43);
          d55 = (d3 * d46);
          d56 = (d38 * d41);
          d57 = (d14 * d44);
          d58 = (d3 * d47);
          d59 = (d35 * d41);
          d60 = (d14 * d45);
          d61 = (d3 * d48);
          d41 = (d34 * d41);
          d62 = (d14 * d1);
          d63 = (d3 * d12);
          d64 = (d32 * d42);
          d65 = (d24 * d43);
          d66 = (d3 * d13);
          d67 = (d38 * d42);
          d68 = (d24 * d44);
          d69 = (d3 * d49);
          d70 = (d35 * d42);
          d71 = (d24 * d45);
          d72 = (d3 * d50);
          d42 = (d34 * d42);
          d73 = (d24 * d1);
          d74 = (d3 * d22);
          d75 = (d38 * d43);
          d76 = (d32 * d44);
          d77 = (d3 * d23);
          d78 = (d35 * d43);
          d79 = (d32 * d45);
          d80 = (d3 * d51);
          d43 = (d34 * d43);
          d81 = (d32 * d1);
          d82 = (d3 * d30);
          d83 = (d35 * d44);
          d84 = (d38 * d45);
          d85 = (d3 * d31);
          d44 = (d34 * d44);
          d86 = (d38 * d1);
          d87 = (d3 * d36);
          d45 = (d34 * d45);
          d1 = (d35 * d1);
          d3 = (d3 * d37);
          d88 = (d32 * d2);
          d89 = (d24 * d46);
          d90 = (d14 * d13);
          d91 = (d38 * d2);
          d92 = (d24 * d47);
          d93 = (d14 * d49);
          d94 = (d35 * d2);
          d95 = (d24 * d48);
          d96 = (d14 * d50);
          d2 = (d34 * d2);
          d97 = (d24 * d12);
          d98 = (d14 * d22);
          d99 = (d38 * d46);
          d100 = (d32 * d47);
          d101 = (d14 * d23);
          d102 = (d35 * d46);
          d103 = (d32 * d48);
          d104 = (d14 * d51);
          d46 = (d34 * d46);
          d105 = (d32 * d12);
          d106 = (d14 * d30);
          d107 = (d35 * d47);
          d108 = (d38 * d48);
          d109 = (d14 * d31);
          d47 = (d34 * d47);
          d110 = (d38 * d12);
          d111 = (d14 * d36);
          d48 = (d34 * d48);
          d12 = (d35 * d12);
          d14 = (d14 * d37);
          d112 = (d38 * d13);
          d113 = (d32 * d49);
          d114 = (d24 * d23);
          d115 = (d35 * d13);
          d116 = (d32 * d50);
          d117 = (d24 * d51);
          d13 = (d34 * d13);
          d118 = (d32 * d22);
          d119 = (d24 * d30);
          d120 = (d35 * d49);
          d121 = (d38 * d50);
          d122 = (d24 * d31);
          d49 = (d34 * d49);
          d123 = (d38 * d22);
          d124 = (d24 * d36);
          d50 = (d34 * d50);
          d22 = (d35 * d22);
          d24 = (d24 * d37);
          d125 = (d35 * d23);
          d126 = (d38 * d51);
          d127 = (d32 * d31);
          d23 = (d34 * d23);
          d128 = (d38 * d30);
          d129 = (d32 * d36);
          d51 = (d34 * d51);
          d30 = (d35 * d30);
          d32 = (d32 * d37);
          d31 = (d34 * d31);
          d34 = (d35 * d36);
          d35 = (d38 * d37);
          d36 = (d39 - d40 + d52);
          d37 = (d53 - d54 + d55);
          d38 = (d56 - d57 + d58);
          d39 = (d59 - d60 + d61);
          d40 = (d41 - d62 + d63);
          d41 = (d64 - d65 + d66);
          d52 = (d67 - d68 + d69);
          d53 = (d70 - d71 + d72);
          d42 = (d42 - d73 + d74);
          d54 = (d75 - d76 + d77);
          d55 = (d78 - d79 + d80);
          d43 = (d43 - d81 + d82);
          d56 = (d83 - d84 + d85);
          d44 = (d44 - d86 + d87);
          d1 = (d45 - d1 + d3);
          d3 = (d88 - d89 + d90);
          d45 = (d91 - d92 + d93);
          d57 = (d94 - d95 + d96);
          d2 = (d2 - d97 + d98);
          d58 = (d99 - d100 + d101);
          d59 = (d102 - d103 + d104);
          d46 = (d46 - d105 + d106);
          d60 = (d107 - d108 + d109);
          d47 = (d47 - d110 + d111);
          d12 = (d48 - d12 + d14);
          d14 = (d112 - d113 + d114);
          d48 = (d115 - d116 + d117);
          d13 = (d13 - d118 + d119);
          d61 = (d120 - d121 + d122);
          d49 = (d49 - d123 + d124);
          d22 = (d50 - d22 + d24);
          d24 = (d125 - d126 + d127);
          d23 = (d23 - d128 + d129);
          d30 = (d51 - d30 + d32);
          d31 = (d31 - d34 + d35);
          d32 = (d33 * d36);
          d34 = (d25 * d37);
          d35 = (d15 * d41);
          d50 = (d4 * d3);
          d51 = (d29 * d36);
          d62 = (d25 * d38);
          d63 = (d15 * d52);
          d64 = (d4 * d45);
          d65 = (d28 * d36);
          d66 = (d25 * d39);
          d67 = (d15 * d53);
          d68 = (d4 * d57);
          d36 = (d27 * d36);
          d69 = (d25 * d40);
          d70 = (d15 * d42);
          d71 = (d4 * d2);
          d72 = (d29 * d37);
          d73 = (d33 * d38);
          d74 = (d15 * d54);
          d75 = (d4 * d58);
          d76 = (d28 * d37);
          d77 = (d33 * d39);
          d78 = (d15 * d55);
          d79 = (d4 * d59);
          d37 = (d27 * d37);
          d80 = (d33 * d40);
          d81 = (d15 * d43);
          d82 = (d4 * d46);
          d83 = (d28 * d38);
          d84 = (d29 * d39);
          d85 = (d15 * d56);
          d86 = (d4 * d60);
          d38 = (d27 * d38);
          d87 = (d29 * d40);
          d88 = (d15 * d44);
          d89 = (d4 * d47);
          d39 = (d27 * d39);
          d40 = (d28 * d40);
          d90 = (d15 * d1);
          d91 = (d4 * d12);
          d92 = (d29 * d41);
          d93 = (d33 * d52);
          d94 = (d25 * d54);
          d95 = (d4 * d14);
          d96 = (d28 * d41);
          d97 = (d33 * d53);
          d98 = (d25 * d55);
          d99 = (d4 * d48);
          d41 = (d27 * d41);
          d100 = (d33 * d42);
          d101 = (d25 * d43);
          d102 = (d4 * d13);
          d103 = (d28 * d52);
          d104 = (d29 * d53);
          d105 = (d25 * d56);
          d106 = (d4 * d61);
          d52 = (d27 * d52);
          d107 = (d29 * d42);
          d108 = (d25 * d44);
          d109 = (d4 * d49);
          d53 = (d27 * d53);
          d42 = (d28 * d42);
          d110 = (d25 * d1);
          d111 = (d4 * d22);
          d112 = (d28 * d54);
          d113 = (d29 * d55);
          d114 = (d33 * d56);
          d115 = (d4 * d24);
          d54 = (d27 * d54);
          d116 = (d29 * d43);
          d117 = (d33 * d44);
          d118 = (d4 * d23);
          d55 = (d27 * d55);
          d43 = (d28 * d43);
          d119 = (d33 * d1);
          d120 = (d4 * d30);
          d56 = (d27 * d56);
          d44 = (d28 * d44);
          d1 = (d29 * d1);
          d4 = (d4 * d31);
          d121 = (d29 * d3);
          d122 = (d33 * d45);
          d123 = (d25 * d58);
          d124 = (d15 * d14);
          d125 = (d28 * d3);
          d126 = (d33 * d57);
          d127 = (d25 * d59);
          d128 = (d15 * d48);
          d3 = (d27 * d3);
          d129 = (d33 * d2);
          d130 = (d25 * d46);
          d131 = (d15 * d13);
          d132 = (d28 * d45);
          d133 = (d29 * d57);
          d134 = (d25 * d60);
          d135 = (d15 * d61);
          d45 = (d27 * d45);
          d136 = (d29 * d2);
          d137 = (d25 * d47);
          d138 = (d15 * d49);
          d57 = (d27 * d57);
          d2 = (d28 * d2);
          d139 = (d25 * d12);
          d140 = (d15 * d22);
          d141 = (d28 * d58);
          d142 = (d29 * d59);
          d143 = (d33 * d60);
          d144 = (d15 * d24);
          d58 = (d27 * d58);
          d145 = (d29 * d46);
          d146 = (d33 * d47);
          d147 = (d15 * d23);
          d59 = (d27 * d59);
          d46 = (d28 * d46);
          d148 = (d33 * d12);
          d149 = (d15 * d30);
          d60 = (d27 * d60);
          d47 = (d28 * d47);
          d12 = (d29 * d12);
          d15 = (d15 * d31);
          d150 = (d28 * d14);
          d151 = (d29 * d48);
          d152 = (d33 * d61);
          d153 = (d25 * d24);
          d14 = (d27 * d14);
          d154 = (d29 * d13);
          d155 = (d33 * d49);
          d156 = (d25 * d23);
          d48 = (d27 * d48);
          d13 = (d28 * d13);
          d157 = (d33 * d22);
          d158 = (d25 * d30);
          d61 = (d27 * d61);
          d49 = (d28 * d49);
          d22 = (d29 * d22);
          d25 = (d25 * d31);
          d24 = (d27 * d24);
          d23 = (d28 * d23);
          d27 = (d29 * d30);
          d28 = (d33 * d31);
          d29 = (d32 - d34 + d35 - d50);
          d30 = (d51 - d62 + d63 - d64);
          d31 = (d65 - d66 + d67 - d68);
          d32 = (d36 - d69 + d70 - d71);
          d33 = (d72 - d73 + d74 - d75);
          d34 = (d76 - d77 + d78 - d79);
          d35 = (d37 - d80 + d81 - d82);
          d36 = (d83 - d84 + d85 - d86);
          d37 = (d38 - d87 + d88 - d89);
          d38 = (d39 - d40 + d90 - d91);
          d39 = (d92 - d93 + d94 - d95);
          d40 = (d96 - d97 + d98 - d99);
          d41 = (d41 - d100 + d101 - d102);
          d50 = (d103 - d104 + d105 - d106);
          d51 = (d52 - d107 + d108 - d109);
          d42 = (d53 - d42 + d110 - d111);
          d52 = (d112 - d113 + d114 - d115);
          d53 = (d54 - d116 + d117 - d118);
          d43 = (d55 - d43 + d119 - d120);
          d1 = (d56 - d44 + d1 - d4);
          d4 = (d121 - d122 + d123 - d124);
          d44 = (d125 - d126 + d127 - d128);
          d3 = (d3 - d129 + d130 - d131);
          d54 = (d132 - d133 + d134 - d135);
          d45 = (d45 - d136 + d137 - d138);
          d2 = (d57 - d2 + d139 - d140);
          d55 = (d141 - d142 + d143 - d144);
          d56 = (d58 - d145 + d146 - d147);
          d46 = (d59 - d46 + d148 - d149);
          d12 = (d60 - d47 + d12 - d15);
          d15 = (d150 - d151 + d152 - d153);
          d14 = (d14 - d154 + d155 - d156);
          d13 = (d48 - d13 + d157 - d158);
          d22 = (d61 - d49 + d22 - d25);
          d23 = (d24 - d23 + d27 - d28);
          d24 = (d20 * d29);
          d25 = (d21 * d30);
          d27 = (d26 * d33);
          d28 = (d16 * d39);
          d47 = (d5 * d4);
          d48 = (d19 * d29);
          d49 = (d21 * d31);
          d57 = (d26 * d34);
          d58 = (d16 * d40);
          d59 = (d5 * d44);
          d29 = (d18 * d29);
          d60 = (d21 * d32);
          d61 = (d26 * d35);
          d62 = (d16 * d41);
          d63 = (d5 * d3);
          d64 = (d19 * d30);
          d65 = (d20 * d31);
          d66 = (d26 * d36);
          d67 = (d16 * d50);
          d68 = (d5 * d54);
          d30 = (d18 * d30);
          d69 = (d20 * d32);
          d70 = (d26 * d37);
          d71 = (d16 * d51);
          d72 = (d5 * d45);
          d31 = (d18 * d31);
          d32 = (d19 * d32);
          d73 = (d26 * d38);
          d74 = (d16 * d42);
          d75 = (d5 * d2);
          d76 = (d19 * d33);
          d77 = (d20 * d34);
          d78 = (d21 * d36);
          d79 = (d16 * d52);
          d80 = (d5 * d55);
          d33 = (d18 * d33);
          d81 = (d20 * d35);
          d82 = (d21 * d37);
          d83 = (d16 * d53);
          d84 = (d5 * d56);
          d34 = (d18 * d34);
          d35 = (d19 * d35);
          d85 = (d21 * d38);
          d86 = (d16 * d43);
          d87 = (d5 * d46);
          d36 = (d18 * d36);
          d37 = (d19 * d37);
          d38 = (d20 * d38);
          d88 = (d16 * d1);
          d89 = (d5 * d12);
          d90 = (d19 * d39);
          d91 = (d20 * d40);
          d92 = (d21 * d50);
          d93 = (d26 * d52);
          d94 = (d5 * d15);
          d39 = (d18 * d39);
          d95 = (d20 * d41);
          d96 = (d21 * d51);
          d97 = (d26 * d53);
          d98 = (d5 * d14);
          d40 = (d18 * d40);
          d41 = (d19 * d41);
          d99 = (d21 * d42);
          d100 = (d26 * d43);
          d101 = (d5 * d13);
          d50 = (d18 * d50);
          d51 = (d19 * d51);
          d42 = (d20 * d42);
          d102 = (d26 * d1);
          d103 = (d5 * d22);
          d52 = (d18 * d52);
          d53 = (d19 * d53);
          d43 = (d20 * d43);
          d1 = (d21 * d1);
          d5 = (d5 * d23);
          d104 = (d19 * d4);
          d105 = (d20 * d44);
          d106 = (d21 * d54);
          d107 = (d26 * d55);
          d108 = (d16 * d15);
          d4 = (d18 * d4);
          d109 = (d20 * d3);
          d110 = (d21 * d45);
          d111 = (d26 * d56);
          d112 = (d16 * d14);
          d44 = (d18 * d44);
          d3 = (d19 * d3);
          d113 = (d21 * d2);
          d114 = (d26 * d46);
          d115 = (d16 * d13);
          d54 = (d18 * d54);
          d45 = (d19 * d45);
          d2 = (d20 * d2);
          d116 = (d26 * d12);
          d117 = (d16 * d22);
          d55 = (d18 * d55);
          d56 = (d19 * d56);
          d46 = (d20 * d46);
          d12 = (d21 * d12);
          d16 = (d16 * d23);
          d15 = (d18 * d15);
          d14 = (d19 * d14);
          d13 = (d20 * d13);
          d18 = (d21 * d22);
          d19 = (d26 * d23);
          d20 = (d24 - d25 + d27 - d28 + d47);
          d21 = (d48 - d49 + d57 - d58 + d59);
          d22 = (d29 - d60 + d61 - d62 + d63);
          d23 = (d64 - d65 + d66 - d67 + d68);
          d24 = (d30 - d69 + d70 - d71 + d72);
          d25 = (d31 - d32 + d73 - d74 + d75);
          d26 = (d76 - d77 + d78 - d79 + d80);
          d27 = (d33 - d81 + d82 - d83 + d84);
          d28 = (d34 - d35 + d85 - d86 + d87);
          d29 = (d36 - d37 + d38 - d88 + d89);
          d30 = (d90 - d91 + d92 - d93 + d94);
          d31 = (d39 - d95 + d96 - d97 + d98);
          d32 = (d40 - d41 + d99 - d100 + d101);
          d33 = (d50 - d51 + d42 - d102 + d103);
          d1 = (d52 - d53 + d43 - d1 + d5);
          d5 = (d104 - d105 + d106 - d107 + d108);
          d4 = (d4 - d109 + d110 - d111 + d112);
          d3 = (d44 - d3 + d113 - d114 + d115);
          d2 = (d54 - d45 + d2 - d116 + d117);
          d12 = (d55 - d56 + d46 - d12 + d16);
          d13 = (d15 - d14 + d13 - d18 + d19);

          return ((mat[0] * ((d8 * d20) - (d9 * d21) + (d10 * d23)
              - (d11 * d26) + (d17 * d30) - (d6 * d5)))
              - (mat[1] * ((d7 * d20) - (d9 * d22) + (d10 * d24)
                  - (d11 * d27) + (d17 * d31) - (d6 * d4)))
              + (mat[2] * ((d7 * d21) - (d8 * d22) + (d10 * d25)
                  - (d11 * d28) + (d17 * d32) - (d6 * d3)))
              - (mat[3] * ((d7 * d23) - (d8 * d24) + (d9 * d25)
                  - (d11 * d29) + (d17 * d33) - (d6 * d2)))
              + (mat[4] * ((d7 * d26) - (d8 * d27) + (d9 * d28)
                  - (d10 * d29) + (d17 * d1) - (d6 * d12)))
              - (mat[5] * ((d7 * d30) - (d8 * d31) + (d9 * d32)
                  - (d10 * d33) + (d11 * d1) - (d6 * d13))) + (mat[6] * ((d7 * d5)
              - (d8 * d4) + (d9 * d3) - (d10 * d2) + (d11 * d12) - (d17 * d13))));

        }
      }
  /*
   * Tests indicate that the hard coded variant for l=8 is slower than the
   * usage of the gaussian algorithm. l=7 seems still to be a little bit
   * faster than gaussian elimination, so we set the cut-off here.
   */
  /*
   * //l = 8, that means we handle all 8x8 matrices here new IDirectDet() {
   * public double det (double[] mat) { // 64 array hits, 321 +, 448 -,
   * 1016 *, 308 variables double d1, d2, d3, d4, d5, d6, d7, d8, d9, d10,
   * d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24,
   * d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38,
   * d39, d40, d41, d42, d43, d44, d45, d46, d47, d48, d49, d50, d51, d52,
   * d53, d54, d55, d56, d57, d58, d59, d60, d61, d62, d63, d64, d65, d66,
   * d67, d68, d69, d70, d71, d72, d73, d74, d75, d76, d77, d78, d79, d80,
   * d81, d82, d83, d84, d85, d86, d87, d88, d89, d90, d91, d92, d93, d94,
   * d95, d96, d97, d98, d99, d100, d101, d102, d103, d104, d105, d106,
   * d107, d108, d109, d110, d111, d112, d113, d114, d115, d116, d117,
   * d118, d119, d120, d121, d122, d123, d124, d125, d126, d127, d128,
   * d129, d130, d131, d132, d133, d134, d135, d136, d137, d138, d139,
   * d140, d141, d142, d143, d144, d145, d146, d147, d148, d149, d150,
   * d151, d152, d153, d154, d155, d156, d157, d158, d159, d160, d161,
   * d162, d163, d164, d165, d166, d167, d168, d169, d170, d171, d172,
   * d173, d174, d175, d176, d177, d178, d179, d180, d181, d182, d183,
   * d184, d185, d186, d187, d188, d189, d190, d191, d192, d193, d194,
   * d195, d196, d197, d198, d199, d200, d201, d202, d203, d204, d205,
   * d206, d207, d208, d209, d210, d211, d212, d213, d214, d215, d216,
   * d217, d218, d219, d220, d221, d222, d223, d224, d225, d226, d227,
   * d228, d229, d230, d231, d232, d233, d234, d235, d236, d237, d238,
   * d239, d240, d241, d242, d243, d244, d245, d246, d247, d248, d249,
   * d250, d251, d252, d253, d254, d255, d256, d257, d258, d259, d260,
   * d261, d262, d263, d264, d265, d266, d267, d268, d269, d270, d271,
   * d272, d273, d274, d275, d276, d277, d278, d279, d280, d281, d282,
   * d283, d284, d285, d286, d287, d288, d289, d290, d291, d292, d293,
   * d294, d295, d296, d297, d298, d299, d300, d301, d302, d303, d304,
   * d305, d306, d307, d308; d1 = mat[63]; d2 = mat[55]; d3 = mat[47]; d4 =
   * mat[39]; d5 = mat[31]; d6 = mat[23]; d7 = mat[15]; d8 = mat[8]; d9 =
   * mat[9]; d10 = mat[10]; d11 = mat[11]; d12 = mat[12]; d13 = mat[13];
   * d14 = mat[62]; d15 = mat[54]; d16 = mat[46]; d17 = mat[38]; d18 =
   * mat[30]; d19 = mat[22]; d20 = mat[14]; d21 = mat[16]; d22 = mat[17];
   * d23 = mat[18]; d24 = mat[19]; d25 = mat[20]; d26 = mat[61]; d27 =
   * mat[53]; d28 = mat[45]; d29 = mat[37]; d30 = mat[29]; d31 = mat[21];
   * d32 = mat[24]; d33 = mat[25]; d34 = mat[26]; d35 = mat[27]; d36 =
   * mat[60]; d37 = mat[52]; d38 = mat[44]; d39 = mat[36]; d40 = mat[28];
   * d41 = mat[32]; d42 = mat[33]; d43 = mat[34]; d44 = mat[59]; d45 =
   * mat[51]; d46 = mat[43]; d47 = mat[35]; d48 = mat[40]; d49 = mat[41];
   * d50 = mat[58]; d51 = mat[50]; d52 = mat[42]; d53 = mat[48]; d54 =
   * mat[57]; d55 = mat[49]; d56 = mat[56]; d57 = (d15*d1); d58 = (d2*d14);
   * d59 = (d27*d1); d60 = (d2*d26); d61 = (d37*d1); d62 = (d2*d36); d63 =
   * (d45*d1); d64 = (d2*d44); d65 = (d51*d1); d66 = (d2*d50); d67 =
   * (d55*d1); d68 = (d2*d54); d1 = (d53*d1); d2 = (d2*d56); d69 =
   * (d27*d14); d70 = (d15*d26); d71 = (d37*d14); d72 = (d15*d36); d73 =
   * (d45*d14); d74 = (d15*d44); d75 = (d51*d14); d76 = (d15*d50); d77 =
   * (d55*d14); d78 = (d15*d54); d14 = (d53*d14); d15 = (d15*d56); d79 =
   * (d37*d26); d80 = (d27*d36); d81 = (d45*d26); d82 = (d27*d44); d83 =
   * (d51*d26); d84 = (d27*d50); d85 = (d55*d26); d86 = (d27*d54); d26 =
   * (d53*d26); d27 = (d27*d56); d87 = (d45*d36); d88 = (d37*d44); d89 =
   * (d51*d36); d90 = (d37*d50); d91 = (d55*d36); d92 = (d37*d54); d36 =
   * (d53*d36); d37 = (d37*d56); d93 = (d51*d44); d94 = (d45*d50); d95 =
   * (d55*d44); d96 = (d45*d54); d44 = (d53*d44); d45 = (d45*d56); d97 =
   * (d55*d50); d98 = (d51*d54); d50 = (d53*d50); d51 = (d51*d56); d53 =
   * (d53*d54); d54 = (d55*d56); d55 = (d57-d58); d56 = (d59-d60); d57 =
   * (d61-d62); d58 = (d63-d64); d59 = (d65-d66); d60 = (d67-d68); d1 =
   * (d1-d2); d2 = (d69-d70); d61 = (d71-d72); d62 = (d73-d74); d63 =
   * (d75-d76); d64 = (d77-d78); d14 = (d14-d15); d15 = (d79-d80); d65 =
   * (d81-d82); d66 = (d83-d84); d67 = (d85-d86); d26 = (d26-d27); d27 =
   * (d87-d88); d68 = (d89-d90); d69 = (d91-d92); d36 = (d36-d37); d37 =
   * (d93-d94); d70 = (d95-d96); d44 = (d44-d45); d45 = (d97-d98); d50 =
   * (d50-d51); d51 = (d53-d54); d53 = (d28*d55); d54 = (d16*d56); d71 =
   * (d3*d2); d72 = (d38*d55); d73 = (d16*d57); d74 = (d3*d61); d75 =
   * (d46*d55); d76 = (d16*d58); d77 = (d3*d62); d78 = (d52*d55); d79 =
   * (d16*d59); d80 = (d3*d63); d81 = (d49*d55); d82 = (d16*d60); d83 =
   * (d3*d64); d55 = (d48*d55); d84 = (d16*d1); d85 = (d3*d14); d86 =
   * (d38*d56); d87 = (d28*d57); d88 = (d3*d15); d89 = (d46*d56); d90 =
   * (d28*d58); d91 = (d3*d65); d92 = (d52*d56); d93 = (d28*d59); d94 =
   * (d3*d66); d95 = (d49*d56); d96 = (d28*d60); d97 = (d3*d67); d56 =
   * (d48*d56); d98 = (d28*d1); d99 = (d3*d26); d100 = (d46*d57); d101 =
   * (d38*d58); d102 = (d3*d27); d103 = (d52*d57); d104 = (d38*d59); d105 =
   * (d3*d68); d106 = (d49*d57); d107 = (d38*d60); d108 = (d3*d69); d57 =
   * (d48*d57); d109 = (d38*d1); d110 = (d3*d36); d111 = (d52*d58); d112 =
   * (d46*d59); d113 = (d3*d37); d114 = (d49*d58); d115 = (d46*d60); d116 =
   * (d3*d70); d58 = (d48*d58); d117 = (d46*d1); d118 = (d3*d44); d119 =
   * (d49*d59); d120 = (d52*d60); d121 = (d3*d45); d59 = (d48*d59); d122 =
   * (d52*d1); d123 = (d3*d50); d60 = (d48*d60); d1 = (d49*d1); d3 =
   * (d3*d51); d124 = (d38*d2); d125 = (d28*d61); d126 = (d16*d15); d127 =
   * (d46*d2); d128 = (d28*d62); d129 = (d16*d65); d130 = (d52*d2); d131 =
   * (d28*d63); d132 = (d16*d66); d133 = (d49*d2); d134 = (d28*d64); d135 =
   * (d16*d67); d2 = (d48*d2); d136 = (d28*d14); d137 = (d16*d26); d138 =
   * (d46*d61); d139 = (d38*d62); d140 = (d16*d27); d141 = (d52*d61); d142 =
   * (d38*d63); d143 = (d16*d68); d144 = (d49*d61); d145 = (d38*d64); d146 =
   * (d16*d69); d61 = (d48*d61); d147 = (d38*d14); d148 = (d16*d36); d149 =
   * (d52*d62); d150 = (d46*d63); d151 = (d16*d37); d152 = (d49*d62); d153 =
   * (d46*d64); d154 = (d16*d70); d62 = (d48*d62); d155 = (d46*d14); d156 =
   * (d16*d44); d157 = (d49*d63); d158 = (d52*d64); d159 = (d16*d45); d63 =
   * (d48*d63); d160 = (d52*d14); d161 = (d16*d50); d64 = (d48*d64); d14 =
   * (d49*d14); d16 = (d16*d51); d162 = (d46*d15); d163 = (d38*d65); d164 =
   * (d28*d27); d165 = (d52*d15); d166 = (d38*d66); d167 = (d28*d68); d168 =
   * (d49*d15); d169 = (d38*d67); d170 = (d28*d69); d15 = (d48*d15); d171 =
   * (d38*d26); d172 = (d28*d36); d173 = (d52*d65); d174 = (d46*d66); d175 =
   * (d28*d37); d176 = (d49*d65); d177 = (d46*d67); d178 = (d28*d70); d65 =
   * (d48*d65); d179 = (d46*d26); d180 = (d28*d44); d181 = (d49*d66); d182 =
   * (d52*d67); d183 = (d28*d45); d66 = (d48*d66); d184 = (d52*d26); d185 =
   * (d28*d50); d67 = (d48*d67); d26 = (d49*d26); d28 = (d28*d51); d186 =
   * (d52*d27); d187 = (d46*d68); d188 = (d38*d37); d189 = (d49*d27); d190 =
   * (d46*d69); d191 = (d38*d70); d27 = (d48*d27); d192 = (d46*d36); d193 =
   * (d38*d44); d194 = (d49*d68); d195 = (d52*d69); d196 = (d38*d45); d68 =
   * (d48*d68); d197 = (d52*d36); d198 = (d38*d50); d69 = (d48*d69); d36 =
   * (d49*d36); d38 = (d38*d51); d199 = (d49*d37); d200 = (d52*d70); d201 =
   * (d46*d45); d37 = (d48*d37); d202 = (d52*d44); d203 = (d46*d50); d70 =
   * (d48*d70); d44 = (d49*d44); d46 = (d46*d51); d45 = (d48*d45); d48 =
   * (d49*d50); d49 = (d52*d51); d50 = (d53-d54+d71); d51 = (d72-d73+d74);
   * d52 = (d75-d76+d77); d53 = (d78-d79+d80); d54 = (d81-d82+d83); d55 =
   * (d55-d84+d85); d71 = (d86-d87+d88); d72 = (d89-d90+d91); d73 =
   * (d92-d93+d94); d74 = (d95-d96+d97); d56 = (d56-d98+d99); d75 =
   * (d100-d101+d102); d76 = (d103-d104+d105); d77 = (d106-d107+d108); d57 =
   * (d57-d109+d110); d78 = (d111-d112+d113); d79 = (d114-d115+d116); d58 =
   * (d58-d117+d118); d80 = (d119-d120+d121); d59 = (d59-d122+d123); d1 =
   * (d60-d1+d3); d3 = (d124-d125+d126); d60 = (d127-d128+d129); d81 =
   * (d130-d131+d132); d82 = (d133-d134+d135); d2 = (d2-d136+d137); d83 =
   * (d138-d139+d140); d84 = (d141-d142+d143); d85 = (d144-d145+d146); d61 =
   * (d61-d147+d148); d86 = (d149-d150+d151); d87 = (d152-d153+d154); d62 =
   * (d62-d155+d156); d88 = (d157-d158+d159); d63 = (d63-d160+d161); d14 =
   * (d64-d14+d16); d16 = (d162-d163+d164); d64 = (d165-d166+d167); d89 =
   * (d168-d169+d170); d15 = (d15-d171+d172); d90 = (d173-d174+d175); d91 =
   * (d176-d177+d178); d65 = (d65-d179+d180); d92 = (d181-d182+d183); d66 =
   * (d66-d184+d185); d26 = (d67-d26+d28); d28 = (d186-d187+d188); d67 =
   * (d189-d190+d191); d27 = (d27-d192+d193); d93 = (d194-d195+d196); d68 =
   * (d68-d197+d198); d36 = (d69-d36+d38); d38 = (d199-d200+d201); d37 =
   * (d37-d202+d203); d44 = (d70-d44+d46); d45 = (d45-d48+d49); d46 =
   * (d39*d50); d48 = (d29*d51); d49 = (d17*d71); d69 = (d4*d3); d70 =
   * (d47*d50); d94 = (d29*d52); d95 = (d17*d72); d96 = (d4*d60); d97 =
   * (d43*d50); d98 = (d29*d53); d99 = (d17*d73); d100 = (d4*d81); d101 =
   * (d42*d50); d102 = (d29*d54); d103 = (d17*d74); d104 = (d4*d82); d50 =
   * (d41*d50); d105 = (d29*d55); d106 = (d17*d56); d107 = (d4*d2); d108 =
   * (d47*d51); d109 = (d39*d52); d110 = (d17*d75); d111 = (d4*d83); d112 =
   * (d43*d51); d113 = (d39*d53); d114 = (d17*d76); d115 = (d4*d84); d116 =
   * (d42*d51); d117 = (d39*d54); d118 = (d17*d77); d119 = (d4*d85); d51 =
   * (d41*d51); d120 = (d39*d55); d121 = (d17*d57); d122 = (d4*d61); d123 =
   * (d43*d52); d124 = (d47*d53); d125 = (d17*d78); d126 = (d4*d86); d127 =
   * (d42*d52); d128 = (d47*d54); d129 = (d17*d79); d130 = (d4*d87); d52 =
   * (d41*d52); d131 = (d47*d55); d132 = (d17*d58); d133 = (d4*d62); d134 =
   * (d42*d53); d135 = (d43*d54); d136 = (d17*d80); d137 = (d4*d88); d53 =
   * (d41*d53); d138 = (d43*d55); d139 = (d17*d59); d140 = (d4*d63); d54 =
   * (d41*d54); d55 = (d42*d55); d141 = (d17*d1); d142 = (d4*d14); d143 =
   * (d47*d71); d144 = (d39*d72); d145 = (d29*d75); d146 = (d4*d16); d147 =
   * (d43*d71); d148 = (d39*d73); d149 = (d29*d76); d150 = (d4*d64); d151 =
   * (d42*d71); d152 = (d39*d74); d153 = (d29*d77); d154 = (d4*d89); d71 =
   * (d41*d71); d155 = (d39*d56); d156 = (d29*d57); d157 = (d4*d15); d158 =
   * (d43*d72); d159 = (d47*d73); d160 = (d29*d78); d161 = (d4*d90); d162 =
   * (d42*d72); d163 = (d47*d74); d164 = (d29*d79); d165 = (d4*d91); d72 =
   * (d41*d72); d166 = (d47*d56); d167 = (d29*d58); d168 = (d4*d65); d169 =
   * (d42*d73); d170 = (d43*d74); d171 = (d29*d80); d172 = (d4*d92); d73 =
   * (d41*d73); d173 = (d43*d56); d174 = (d29*d59); d175 = (d4*d66); d74 =
   * (d41*d74); d56 = (d42*d56); d176 = (d29*d1); d177 = (d4*d26); d178 =
   * (d43*d75); d179 = (d47*d76); d180 = (d39*d78); d181 = (d4*d28); d182 =
   * (d42*d75); d183 = (d47*d77); d184 = (d39*d79); d185 = (d4*d67); d75 =
   * (d41*d75); d186 = (d47*d57); d187 = (d39*d58); d188 = (d4*d27); d189 =
   * (d42*d76); d190 = (d43*d77); d191 = (d39*d80); d192 = (d4*d93); d76 =
   * (d41*d76); d193 = (d43*d57); d194 = (d39*d59); d195 = (d4*d68); d77 =
   * (d41*d77); d57 = (d42*d57); d196 = (d39*d1); d197 = (d4*d36); d198 =
   * (d42*d78); d199 = (d43*d79); d200 = (d47*d80); d201 = (d4*d38); d78 =
   * (d41*d78); d202 = (d43*d58); d203 = (d47*d59); d204 = (d4*d37); d79 =
   * (d41*d79); d58 = (d42*d58); d205 = (d47*d1); d206 = (d4*d44); d80 =
   * (d41*d80); d59 = (d42*d59); d1 = (d43*d1); d4 = (d4*d45); d207 =
   * (d47*d3); d208 = (d39*d60); d209 = (d29*d83); d210 = (d17*d16); d211 =
   * (d43*d3); d212 = (d39*d81); d213 = (d29*d84); d214 = (d17*d64); d215 =
   * (d42*d3); d216 = (d39*d82); d217 = (d29*d85); d218 = (d17*d89); d3 =
   * (d41*d3); d219 = (d39*d2); d220 = (d29*d61); d221 = (d17*d15); d222 =
   * (d43*d60); d223 = (d47*d81); d224 = (d29*d86); d225 = (d17*d90); d226 =
   * (d42*d60); d227 = (d47*d82); d228 = (d29*d87); d229 = (d17*d91); d60 =
   * (d41*d60); d230 = (d47*d2); d231 = (d29*d62); d232 = (d17*d65); d233 =
   * (d42*d81); d234 = (d43*d82); d235 = (d29*d88); d236 = (d17*d92); d81 =
   * (d41*d81); d237 = (d43*d2); d238 = (d29*d63); d239 = (d17*d66); d82 =
   * (d41*d82); d2 = (d42*d2); d240 = (d29*d14); d241 = (d17*d26); d242 =
   * (d43*d83); d243 = (d47*d84); d244 = (d39*d86); d245 = (d17*d28); d246 =
   * (d42*d83); d247 = (d47*d85); d248 = (d39*d87); d249 = (d17*d67); d83 =
   * (d41*d83); d250 = (d47*d61); d251 = (d39*d62); d252 = (d17*d27); d253 =
   * (d42*d84); d254 = (d43*d85); d255 = (d39*d88); d256 = (d17*d93); d84 =
   * (d41*d84); d257 = (d43*d61); d258 = (d39*d63); d259 = (d17*d68); d85 =
   * (d41*d85); d61 = (d42*d61); d260 = (d39*d14); d261 = (d17*d36); d262 =
   * (d42*d86); d263 = (d43*d87); d264 = (d47*d88); d265 = (d17*d38); d86 =
   * (d41*d86); d266 = (d43*d62); d267 = (d47*d63); d268 = (d17*d37); d87 =
   * (d41*d87); d62 = (d42*d62); d269 = (d47*d14); d270 = (d17*d44); d88 =
   * (d41*d88); d63 = (d42*d63); d14 = (d43*d14); d17 = (d17*d45); d271 =
   * (d43*d16); d272 = (d47*d64); d273 = (d39*d90); d274 = (d29*d28); d275 =
   * (d42*d16); d276 = (d47*d89); d277 = (d39*d91); d278 = (d29*d67); d16 =
   * (d41*d16); d279 = (d47*d15); d280 = (d39*d65); d281 = (d29*d27); d282 =
   * (d42*d64); d283 = (d43*d89); d284 = (d39*d92); d285 = (d29*d93); d64 =
   * (d41*d64); d286 = (d43*d15); d287 = (d39*d66); d288 = (d29*d68); d89 =
   * (d41*d89); d15 = (d42*d15); d289 = (d39*d26); d290 = (d29*d36); d291 =
   * (d42*d90); d292 = (d43*d91); d293 = (d47*d92); d294 = (d29*d38); d90 =
   * (d41*d90); d295 = (d43*d65); d296 = (d47*d66); d297 = (d29*d37); d91 =
   * (d41*d91); d65 = (d42*d65); d298 = (d47*d26); d299 = (d29*d44); d92 =
   * (d41*d92); d66 = (d42*d66); d26 = (d43*d26); d29 = (d29*d45); d300 =
   * (d42*d28); d301 = (d43*d67); d302 = (d47*d93); d303 = (d39*d38); d28 =
   * (d41*d28); d304 = (d43*d27); d305 = (d47*d68); d306 = (d39*d37); d67 =
   * (d41*d67); d27 = (d42*d27); d307 = (d47*d36); d308 = (d39*d44); d93 =
   * (d41*d93); d68 = (d42*d68); d36 = (d43*d36); d39 = (d39*d45); d38 =
   * (d41*d38); d37 = (d42*d37); d41 = (d43*d44); d42 = (d47*d45); d43 =
   * (d46-d48+d49-d69); d44 = (d70-d94+d95-d96); d45 = (d97-d98+d99-d100);
   * d46 = (d101-d102+d103-d104); d47 = (d50-d105+d106-d107); d48 =
   * (d108-d109+d110-d111); d49 = (d112-d113+d114-d115); d50 =
   * (d116-d117+d118-d119); d51 = (d51-d120+d121-d122); d69 =
   * (d123-d124+d125-d126); d70 = (d127-d128+d129-d130); d52 =
   * (d52-d131+d132-d133); d94 = (d134-d135+d136-d137); d53 =
   * (d53-d138+d139-d140); d54 = (d54-d55+d141-d142); d55 =
   * (d143-d144+d145-d146); d95 = (d147-d148+d149-d150); d96 =
   * (d151-d152+d153-d154); d71 = (d71-d155+d156-d157); d97 =
   * (d158-d159+d160-d161); d98 = (d162-d163+d164-d165); d72 =
   * (d72-d166+d167-d168); d99 = (d169-d170+d171-d172); d73 =
   * (d73-d173+d174-d175); d56 = (d74-d56+d176-d177); d74 =
   * (d178-d179+d180-d181); d100 = (d182-d183+d184-d185); d75 =
   * (d75-d186+d187-d188); d101 = (d189-d190+d191-d192); d76 =
   * (d76-d193+d194-d195); d57 = (d77-d57+d196-d197); d77 =
   * (d198-d199+d200-d201); d78 = (d78-d202+d203-d204); d58 =
   * (d79-d58+d205-d206); d1 = (d80-d59+d1-d4); d4 = (d207-d208+d209-d210);
   * d59 = (d211-d212+d213-d214); d79 = (d215-d216+d217-d218); d3 =
   * (d3-d219+d220-d221); d80 = (d222-d223+d224-d225); d102 =
   * (d226-d227+d228-d229); d60 = (d60-d230+d231-d232); d103 =
   * (d233-d234+d235-d236); d81 = (d81-d237+d238-d239); d2 =
   * (d82-d2+d240-d241); d82 = (d242-d243+d244-d245); d104 =
   * (d246-d247+d248-d249); d83 = (d83-d250+d251-d252); d105 =
   * (d253-d254+d255-d256); d84 = (d84-d257+d258-d259); d61 =
   * (d85-d61+d260-d261); d85 = (d262-d263+d264-d265); d86 =
   * (d86-d266+d267-d268); d62 = (d87-d62+d269-d270); d14 =
   * (d88-d63+d14-d17); d17 = (d271-d272+d273-d274); d63 =
   * (d275-d276+d277-d278); d16 = (d16-d279+d280-d281); d87 =
   * (d282-d283+d284-d285); d64 = (d64-d286+d287-d288); d15 =
   * (d89-d15+d289-d290); d88 = (d291-d292+d293-d294); d89 =
   * (d90-d295+d296-d297); d65 = (d91-d65+d298-d299); d26 =
   * (d92-d66+d26-d29); d29 = (d300-d301+d302-d303); d28 =
   * (d28-d304+d305-d306); d27 = (d67-d27+d307-d308); d36 =
   * (d93-d68+d36-d39); d37 = (d38-d37+d41-d42); d38 = (d35*d43); d39 =
   * (d40*d44); d41 = (d30*d48); d42 = (d18*d55); d66 = (d5*d4); d67 =
   * (d34*d43); d68 = (d40*d45); d90 = (d30*d49); d91 = (d18*d95); d92 =
   * (d5*d59); d93 = (d33*d43); d106 = (d40*d46); d107 = (d30*d50); d108 =
   * (d18*d96); d109 = (d5*d79); d43 = (d32*d43); d110 = (d40*d47); d111 =
   * (d30*d51); d112 = (d18*d71); d113 = (d5*d3); d114 = (d34*d44); d115 =
   * (d35*d45); d116 = (d30*d69); d117 = (d18*d97); d118 = (d5*d80); d119 =
   * (d33*d44); d120 = (d35*d46); d121 = (d30*d70); d122 = (d18*d98); d123 =
   * (d5*d102); d44 = (d32*d44); d124 = (d35*d47); d125 = (d30*d52); d126 =
   * (d18*d72); d127 = (d5*d60); d128 = (d33*d45); d129 = (d34*d46); d130 =
   * (d30*d94); d131 = (d18*d99); d132 = (d5*d103); d45 = (d32*d45); d133 =
   * (d34*d47); d134 = (d30*d53); d135 = (d18*d73); d136 = (d5*d81); d46 =
   * (d32*d46); d47 = (d33*d47); d137 = (d30*d54); d138 = (d18*d56); d139 =
   * (d5*d2); d140 = (d34*d48); d141 = (d35*d49); d142 = (d40*d69); d143 =
   * (d18*d74); d144 = (d5*d82); d145 = (d33*d48); d146 = (d35*d50); d147 =
   * (d40*d70); d148 = (d18*d100); d149 = (d5*d104); d48 = (d32*d48); d150 =
   * (d35*d51); d151 = (d40*d52); d152 = (d18*d75); d153 = (d5*d83); d154 =
   * (d33*d49); d155 = (d34*d50); d156 = (d40*d94); d157 = (d18*d101); d158 =
   * (d5*d105); d49 = (d32*d49); d159 = (d34*d51); d160 = (d40*d53); d161 =
   * (d18*d76); d162 = (d5*d84); d50 = (d32*d50); d51 = (d33*d51); d163 =
   * (d40*d54); d164 = (d18*d57); d165 = (d5*d61); d166 = (d33*d69); d167 =
   * (d34*d70); d168 = (d35*d94); d169 = (d18*d77); d170 = (d5*d85); d69 =
   * (d32*d69); d171 = (d34*d52); d172 = (d35*d53); d173 = (d18*d78); d174 =
   * (d5*d86); d70 = (d32*d70); d52 = (d33*d52); d175 = (d35*d54); d176 =
   * (d18*d58); d177 = (d5*d62); d94 = (d32*d94); d53 = (d33*d53); d54 =
   * (d34*d54); d178 = (d18*d1); d179 = (d5*d14); d180 = (d34*d55); d181 =
   * (d35*d95); d182 = (d40*d97); d183 = (d30*d74); d184 = (d5*d17); d185 =
   * (d33*d55); d186 = (d35*d96); d187 = (d40*d98); d188 = (d30*d100); d189 =
   * (d5*d63); d55 = (d32*d55); d190 = (d35*d71); d191 = (d40*d72); d192 =
   * (d30*d75); d193 = (d5*d16); d194 = (d33*d95); d195 = (d34*d96); d196 =
   * (d40*d99); d197 = (d30*d101); d198 = (d5*d87); d95 = (d32*d95); d199 =
   * (d34*d71); d200 = (d40*d73); d201 = (d30*d76); d202 = (d5*d64); d96 =
   * (d32*d96); d71 = (d33*d71); d203 = (d40*d56); d204 = (d30*d57); d205 =
   * (d5*d15); d206 = (d33*d97); d207 = (d34*d98); d208 = (d35*d99); d209 =
   * (d30*d77); d210 = (d5*d88); d97 = (d32*d97); d211 = (d34*d72); d212 =
   * (d35*d73); d213 = (d30*d78); d214 = (d5*d89); d98 = (d32*d98); d72 =
   * (d33*d72); d215 = (d35*d56); d216 = (d30*d58); d217 = (d5*d65); d99 =
   * (d32*d99); d73 = (d33*d73); d56 = (d34*d56); d218 = (d30*d1); d219 =
   * (d5*d26); d220 = (d33*d74); d221 = (d34*d100); d222 = (d35*d101); d223 =
   * (d40*d77); d224 = (d5*d29); d74 = (d32*d74); d225 = (d34*d75); d226 =
   * (d35*d76); d227 = (d40*d78); d228 = (d5*d28); d100 = (d32*d100); d75 =
   * (d33*d75); d229 = (d35*d57); d230 = (d40*d58); d231 = (d5*d27); d101 =
   * (d32*d101); d76 = (d33*d76); d57 = (d34*d57); d232 = (d40*d1); d233 =
   * (d5*d36); d77 = (d32*d77); d78 = (d33*d78); d58 = (d34*d58); d1 =
   * (d35*d1); d5 = (d5*d37); d234 = (d34*d4); d235 = (d35*d59); d236 =
   * (d40*d80); d237 = (d30*d82); d238 = (d18*d17); d239 = (d33*d4); d240 =
   * (d35*d79); d241 = (d40*d102); d242 = (d30*d104); d243 = (d18*d63); d4 =
   * (d32*d4); d244 = (d35*d3); d245 = (d40*d60); d246 = (d30*d83); d247 =
   * (d18*d16); d248 = (d33*d59); d249 = (d34*d79); d250 = (d40*d103); d251 =
   * (d30*d105); d252 = (d18*d87); d59 = (d32*d59); d253 = (d34*d3); d254 =
   * (d40*d81); d255 = (d30*d84); d256 = (d18*d64); d79 = (d32*d79); d3 =
   * (d33*d3); d257 = (d40*d2); d258 = (d30*d61); d259 = (d18*d15); d260 =
   * (d33*d80); d261 = (d34*d102); d262 = (d35*d103); d263 = (d30*d85);
   * d264 = (d18*d88); d80 = (d32*d80); d265 = (d34*d60); d266 = (d35*d81);
   * d267 = (d30*d86); d268 = (d18*d89); d102 = (d32*d102); d60 =
   * (d33*d60); d269 = (d35*d2); d270 = (d30*d62); d271 = (d18*d65); d103 =
   * (d32*d103); d81 = (d33*d81); d2 = (d34*d2); d272 = (d30*d14); d273 =
   * (d18*d26); d274 = (d33*d82); d275 = (d34*d104); d276 = (d35*d105);
   * d277 = (d40*d85); d278 = (d18*d29); d82 = (d32*d82); d279 = (d34*d83);
   * d280 = (d35*d84); d281 = (d40*d86); d282 = (d18*d28); d104 =
   * (d32*d104); d83 = (d33*d83); d283 = (d35*d61); d284 = (d40*d62); d285 =
   * (d18*d27); d105 = (d32*d105); d84 = (d33*d84); d61 = (d34*d61); d286 =
   * (d40*d14); d287 = (d18*d36); d85 = (d32*d85); d86 = (d33*d86); d62 =
   * (d34*d62); d14 = (d35*d14); d18 = (d18*d37); d288 = (d33*d17); d289 =
   * (d34*d63); d290 = (d35*d87); d291 = (d40*d88); d292 = (d30*d29); d17 =
   * (d32*d17); d293 = (d34*d16); d294 = (d35*d64); d295 = (d40*d89); d296 =
   * (d30*d28); d63 = (d32*d63); d16 = (d33*d16); d297 = (d35*d15); d298 =
   * (d40*d65); d299 = (d30*d27); d87 = (d32*d87); d64 = (d33*d64); d15 =
   * (d34*d15); d300 = (d40*d26); d301 = (d30*d36); d88 = (d32*d88); d89 =
   * (d33*d89); d65 = (d34*d65); d26 = (d35*d26); d30 = (d30*d37); d29 =
   * (d32*d29); d28 = (d33*d28); d27 = (d34*d27); d32 = (d35*d36); d33 =
   * (d40*d37); d34 = (d38-d39+d41-d42+d66); d35 = (d67-d68+d90-d91+d92);
   * d36 = (d93-d106+d107-d108+d109); d37 = (d43-d110+d111-d112+d113); d38 =
   * (d114-d115+d116-d117+d118); d39 = (d119-d120+d121-d122+d123); d40 =
   * (d44-d124+d125-d126+d127); d41 = (d128-d129+d130-d131+d132); d42 =
   * (d45-d133+d134-d135+d136); d43 = (d46-d47+d137-d138+d139); d44 =
   * (d140-d141+d142-d143+d144); d45 = (d145-d146+d147-d148+d149); d46 =
   * (d48-d150+d151-d152+d153); d47 = (d154-d155+d156-d157+d158); d48 =
   * (d49-d159+d160-d161+d162); d49 = (d50-d51+d163-d164+d165); d50 =
   * (d166-d167+d168-d169+d170); d51 = (d69-d171+d172-d173+d174); d52 =
   * (d70-d52+d175-d176+d177); d53 = (d94-d53+d54-d178+d179); d54 =
   * (d180-d181+d182-d183+d184); d66 = (d185-d186+d187-d188+d189); d55 =
   * (d55-d190+d191-d192+d193); d67 = (d194-d195+d196-d197+d198); d68 =
   * (d95-d199+d200-d201+d202); d69 = (d96-d71+d203-d204+d205); d70 =
   * (d206-d207+d208-d209+d210); d71 = (d97-d211+d212-d213+d214); d72 =
   * (d98-d72+d215-d216+d217); d56 = (d99-d73+d56-d218+d219); d73 =
   * (d220-d221+d222-d223+d224); d74 = (d74-d225+d226-d227+d228); d75 =
   * (d100-d75+d229-d230+d231); d57 = (d101-d76+d57-d232+d233); d1 =
   * (d77-d78+d58-d1+d5); d5 = (d234-d235+d236-d237+d238); d58 =
   * (d239-d240+d241-d242+d243); d4 = (d4-d244+d245-d246+d247); d76 =
   * (d248-d249+d250-d251+d252); d59 = (d59-d253+d254-d255+d256); d3 =
   * (d79-d3+d257-d258+d259); d77 = (d260-d261+d262-d263+d264); d78 =
   * (d80-d265+d266-d267+d268); d60 = (d102-d60+d269-d270+d271); d2 =
   * (d103-d81+d2-d272+d273); d79 = (d274-d275+d276-d277+d278); d80 =
   * (d82-d279+d280-d281+d282); d81 = (d104-d83+d283-d284+d285); d61 =
   * (d105-d84+d61-d286+d287); d14 = (d85-d86+d62-d14+d18); d18 =
   * (d288-d289+d290-d291+d292); d17 = (d17-d293+d294-d295+d296); d16 =
   * (d63-d16+d297-d298+d299); d15 = (d87-d64+d15-d300+d301); d26 =
   * (d88-d89+d65-d26+d30); d27 = (d29-d28+d27-d32+d33); d28 = (d23*d34);
   * d29 = (d24*d35); d30 = (d25*d38); d32 = (d31*d44); d33 = (d19*d54);
   * d62 = (d6*d5); d63 = (d22*d34); d64 = (d24*d36); d65 = (d25*d39); d82 =
   * (d31*d45); d83 = (d19*d66); d84 = (d6*d58); d34 = (d21*d34); d85 =
   * (d24*d37); d86 = (d25*d40); d87 = (d31*d46); d88 = (d19*d55); d89 =
   * (d6*d4); d90 = (d22*d35); d91 = (d23*d36); d92 = (d25*d41); d93 =
   * (d31*d47); d94 = (d19*d67); d95 = (d6*d76); d35 = (d21*d35); d96 =
   * (d23*d37); d97 = (d25*d42); d98 = (d31*d48); d99 = (d19*d68); d100 =
   * (d6*d59); d36 = (d21*d36); d37 = (d22*d37); d101 = (d25*d43); d102 =
   * (d31*d49); d103 = (d19*d69); d104 = (d6*d3); d105 = (d22*d38); d106 =
   * (d23*d39); d107 = (d24*d41); d108 = (d31*d50); d109 = (d19*d70); d110 =
   * (d6*d77); d38 = (d21*d38); d111 = (d23*d40); d112 = (d24*d42); d113 =
   * (d31*d51); d114 = (d19*d71); d115 = (d6*d78); d39 = (d21*d39); d40 =
   * (d22*d40); d116 = (d24*d43); d117 = (d31*d52); d118 = (d19*d72); d119 =
   * (d6*d60); d41 = (d21*d41); d42 = (d22*d42); d43 = (d23*d43); d120 =
   * (d31*d53); d121 = (d19*d56); d122 = (d6*d2); d123 = (d22*d44); d124 =
   * (d23*d45); d125 = (d24*d47); d126 = (d25*d50); d127 = (d19*d73); d128 =
   * (d6*d79); d44 = (d21*d44); d129 = (d23*d46); d130 = (d24*d48); d131 =
   * (d25*d51); d132 = (d19*d74); d133 = (d6*d80); d45 = (d21*d45); d46 =
   * (d22*d46); d134 = (d24*d49); d135 = (d25*d52); d136 = (d19*d75); d137 =
   * (d6*d81); d47 = (d21*d47); d48 = (d22*d48); d49 = (d23*d49); d138 =
   * (d25*d53); d139 = (d19*d57); d140 = (d6*d61); d50 = (d21*d50); d51 =
   * (d22*d51); d52 = (d23*d52); d53 = (d24*d53); d141 = (d19*d1); d142 =
   * (d6*d14); d143 = (d22*d54); d144 = (d23*d66); d145 = (d24*d67); d146 =
   * (d25*d70); d147 = (d31*d73); d148 = (d6*d18); d54 = (d21*d54); d149 =
   * (d23*d55); d150 = (d24*d68); d151 = (d25*d71); d152 = (d31*d74); d153 =
   * (d6*d17); d66 = (d21*d66); d55 = (d22*d55); d154 = (d24*d69); d155 =
   * (d25*d72); d156 = (d31*d75); d157 = (d6*d16); d67 = (d21*d67); d68 =
   * (d22*d68); d69 = (d23*d69); d158 = (d25*d56); d159 = (d31*d57); d160 =
   * (d6*d15); d70 = (d21*d70); d71 = (d22*d71); d72 = (d23*d72); d56 =
   * (d24*d56); d161 = (d31*d1); d162 = (d6*d26); d73 = (d21*d73); d74 =
   * (d22*d74); d75 = (d23*d75); d57 = (d24*d57); d1 = (d25*d1); d6 =
   * (d6*d27); d163 = (d22*d5); d164 = (d23*d58); d165 = (d24*d76); d166 =
   * (d25*d77); d167 = (d31*d79); d168 = (d19*d18); d5 = (d21*d5); d169 =
   * (d23*d4); d170 = (d24*d59); d171 = (d25*d78); d172 = (d31*d80); d173 =
   * (d19*d17); d58 = (d21*d58); d4 = (d22*d4); d174 = (d24*d3); d175 =
   * (d25*d60); d176 = (d31*d81); d177 = (d19*d16); d76 = (d21*d76); d59 =
   * (d22*d59); d3 = (d23*d3); d178 = (d25*d2); d179 = (d31*d61); d180 =
   * (d19*d15); d77 = (d21*d77); d78 = (d22*d78); d60 = (d23*d60); d2 =
   * (d24*d2); d181 = (d31*d14); d182 = (d19*d26); d79 = (d21*d79); d80 =
   * (d22*d80); d81 = (d23*d81); d61 = (d24*d61); d14 = (d25*d14); d19 =
   * (d19*d27); d18 = (d21*d18); d17 = (d22*d17); d16 = (d23*d16); d15 =
   * (d24*d15); d21 = (d25*d26); d22 = (d31*d27); d23 =
   * (d28-d29+d30-d32+d33-d62); d24 = (d63-d64+d65-d82+d83-d84); d25 =
   * (d34-d85+d86-d87+d88-d89); d26 = (d90-d91+d92-d93+d94-d95); d27 =
   * (d35-d96+d97-d98+d99-d100); d28 = (d36-d37+d101-d102+d103-d104); d29 =
   * (d105-d106+d107-d108+d109-d110); d30 = (d38-d111+d112-d113+d114-d115);
   * d31 = (d39-d40+d116-d117+d118-d119); d32 =
   * (d41-d42+d43-d120+d121-d122); d33 = (d123-d124+d125-d126+d127-d128);
   * d34 = (d44-d129+d130-d131+d132-d133); d35 =
   * (d45-d46+d134-d135+d136-d137); d36 = (d47-d48+d49-d138+d139-d140); d37 =
   * (d50-d51+d52-d53+d141-d142); d38 = (d143-d144+d145-d146+d147-d148);
   * d39 = (d54-d149+d150-d151+d152-d153); d40 =
   * (d66-d55+d154-d155+d156-d157); d41 = (d67-d68+d69-d158+d159-d160); d42 =
   * (d70-d71+d72-d56+d161-d162); d1 = (d73-d74+d75-d57+d1-d6); d6 =
   * (d163-d164+d165-d166+d167-d168); d5 = (d5-d169+d170-d171+d172-d173);
   * d4 = (d58-d4+d174-d175+d176-d177); d3 = (d76-d59+d3-d178+d179-d180);
   * d2 = (d77-d78+d60-d2+d181-d182); d14 = (d79-d80+d81-d61+d14-d19); d15 =
   * (d18-d17+d16-d15+d21-d22); return
   * ((mat[0]*((d9*d23)-(d10*d24)+(d11*d26)-(d12*d29)+
   * (d13*d33)-(d20*d38)+(d7*d6)))-(mat[1]*((d8*d23)-
   * (d10*d25)+(d11*d27)-(d12*d30)+(d13*d34)-(d20*d39)+
   * (d7*d5)))+(mat[2]*((d8*d24)-(d9*d25)+(d11*d28)-(d12*
   * d31)+(d13*d35)-(d20*d40)+(d7*d4)))-(mat[3]*((d8*
   * d26)-(d9*d27)+(d10*d28)-(d12*d32)+(d13*d36)-(d20*d41)+
   * (d7*d3)))+(mat[4]*((d8*d29)-(d9*d30)+(d10*d31)-(d11*
   * d32)+(d13*d37)-(d20*d42)+(d7*d2)))-(mat[5]*((d8*
   * d33)-(d9*d34)+(d10*d35)-(d11*d36)+(d12*d37)-(d20*d1)+
   * (d7*d14)))+(mat[6]*((d8*d38)-(d9*d39)+(d10*d40)-
   * (d11*d41)+(d12*d42)-(d13*d1)+(d7*d15)))-(mat[7]*
   * ((d8*d6)-(d9*d5)+(d10*d4)-(d11*d3)+(d12*d2)-(d13*d14)+ (d20*d15)))); } }
   */

  };

  /**
   * calculates the determinante of the matrix by using the gaussian
   * elimination algorithm
   * 
   * @param mat
   *          the data of the matrix
   * @param l =
   *          m, n = height and width of the matrix
   * @return the determinante
   */
  private static double gauss(double mat[], int l) {
    double s, t, det;
    int i, j, k, a, b, c, d;
    double temp[];

    temp = new double[(i = (l * l)) + l];
    System.arraycopy(mat, 0, temp, 0, i);

    det = 1.0;
    a = 0;
    for (i = 0; i < l; i++) {
      s = temp[a];

      if (s == 0) {
        b = a;
        for (j = (i + 1); j < l; j++) {
          b += l;
          s = temp[b];
          if (s != 0)
            break;
        }
        if (s == 0)
          return 0;

        det = -det;
        d = l - i;
        c = l * l;
        System.arraycopy(temp, b, temp, c, d);
        System.arraycopy(temp, a, temp, b, d);
        System.arraycopy(temp, c, temp, a, d);
      }

      det *= s;

      b = a;
      for (j = (i + 1); j < l; j++) {
        b += l;
        t = -(temp[b] / s);
        if (t != 0) {
          temp[b] = 0;
          k = l - i - 1;
          d = b + k;
          c = a + k;
          for (; k >= 0; k--) {
            temp[d--] += t * temp[c--];
          }
        }
      }

      a += l + 1;
    }

    return det;
  }

  /**
   * calculates the determinante of the matrix by using the optimal
   * algorithm
   * 
   * @param mat
   *          the data of the matrix
   * @param l =
   *          m, n = height and width of the matrix
   * @return the determinante
   */
  public static double det(double mat[], int l) {
    if (l < 8)
      return FAST_DET[l - 1].det(mat);

    if (l > LU_THRESHOLD)
      return new LUDecomposition(l, l, mat).det();
    return gauss(mat, l);
  }

}
