
package de.vs.unikassel.query.client.callback_interface.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CallbackService", targetNamespace = "http://callback_interface.client.query.unikassel.vs.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CallbackService {


    /**
     * 
     * @param bpelDocument
     */
    @WebMethod
    public void result(
        @WebParam(name = "bpelDocument", partName = "bpelDocument")
        String bpelDocument);

}
