
package de.vs.unikassel.query.server.stub;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@SuppressWarnings("static-access")
@WebServiceClient(name = "CompositionSystemInterfaceService", targetNamespace = "http://server.query.unikassel.vs.de/", wsdlLocation = "de/vs/unikassel/query/server/CompositionSystemInterfaceService.wsdl")
public class CompositionSystemInterfaceService
    extends Service
{

    private final static URL COMPOSITIONSYSTEMINTERFACESERVICE_WSDL_LOCATION;    

    static {
        COMPOSITIONSYSTEMINTERFACESERVICE_WSDL_LOCATION = CompositionSystemInterfaceService.class.getClassLoader().getSystemResource("de/vs/unikassel/query/server/CompositionSystemInterfaceService.wsdl");
    }

    public CompositionSystemInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompositionSystemInterfaceService() {
        super(COMPOSITIONSYSTEMINTERFACESERVICE_WSDL_LOCATION, new QName("http://server.query.unikassel.vs.de/", "CompositionSystemInterfaceService"));
    }

    /**
     * 
     * @return
     *     returns CompositionSystem
     */
    @WebEndpoint(name = "CompositionSystemPort")
    public CompositionSystem getCompositionSystemPort() {
        return super.getPort(new QName("http://server.query.unikassel.vs.de/", "CompositionSystemPort"), CompositionSystem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompositionSystem
     */
    @WebEndpoint(name = "CompositionSystemPort")
    public CompositionSystem getCompositionSystemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.query.unikassel.vs.de/", "CompositionSystemPort"), CompositionSystem.class, features);
    }

}
