
package de.vs.unikassel.query.server.stub;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CompositionSystem", targetNamespace = "http://server.query.unikassel.vs.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CompositionSystem {


    /**
     * 
     * @param wsdlQuery
     * @param callbackURL
     */
    @WebMethod
    @Oneway
    public void startQuery(
        @WebParam(name = "wsdlQuery", partName = "wsdlQuery")
        String wsdlQuery,
        @WebParam(name = "callbackURL", partName = "callbackURL")
        String callbackURL);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean stopComposition();

    /**
     * 
     * @param wsdlServiceDescriptionsURL
     * @param owlTaxonomyURL
     * @param wslaSLAgreementsURL
     */
    @WebMethod
    @Oneway
    public void initialize(
        @WebParam(name = "wsdlServiceDescriptionsURL", partName = "wsdlServiceDescriptionsURL")
        String wsdlServiceDescriptionsURL,
        @WebParam(name = "owlTaxonomyURL", partName = "owlTaxonomyURL")
        String owlTaxonomyURL,
        @WebParam(name = "wslaSLAgreementsURL", partName = "wslaSLAgreementsURL")
        String wslaSLAgreementsURL);

}
